TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.db_process,DBProcessTrain
  num_workers: 8
  img_set_dir: F:\数据集\字符检测数据集\苏州电子围网车牌关键点数据集/
  label_file_path: F:\数据集\字符检测数据集\苏州电子围网车牌关键点数据集/train_icdar2015_label.txt

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: F:\数据集\字符检测数据集\苏州电子围网车牌关键点数据集/
  label_file_path: F:\数据集\字符检测数据集\苏州电子围网车牌关键点数据集/test_icdar2015_label.txt
  test_image_shape: [640, 640]
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  infer_img:
  img_set_dir: F:\数据集\字符检测数据集\苏州电子围网车牌关键点数据集/
  label_file_path: F:\数据集\字符检测数据集\苏州电子围网车牌关键点数据集/test_icdar2015_label.txt
  test_image_shape: [640, 640]
  do_eval: True
