Global:
  use_gpu: True
  epoch_num: 10000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /home/samples/sda2/Models/Paddle2.1/箱号识别模型/水平箱号识别模型/mv3_tps_bilstm_ctc/2021-08-06/
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path:
  character_type: en
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: /home/samples/sda2/Models/Paddle2.1/箱号识别模型/水平箱号识别模型/mv3_tps_bilstm_ctc/predicts_mv3_tps_bilstm_ctc.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: STARNet
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: small
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0.0004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/samples/sda2/Data/OCR/ContainerOCR/2021-03-10/OCR/OCRH
    label_file_list: ["/home/samples/sda2/Data/OCR/ContainerOCR/2021-03-10/OCR/OCRH/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 400]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: True
    num_workers: 2
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/samples/sda2/Data/OCR/ContainerOCR/2021-03-10/OCR/OCRH
    label_file_list: ["/home/samples/sda2/Data/OCR/ContainerOCR/2021-03-10/OCR/OCRH/rec_gt_test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 400]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 0
    use_shared_memory: False
